export const SEATS_DATA = {
  premium: {
    available_seats: 11,
    row_one: [
      {
        id: 1,
        row: 1,
        row_text: "row_one",
        seat: "A",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 2,
        row: 1,
        row_text: "row_one",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 3,
        row: 1,
        row_text: "row_one",
        seat: "C",
        ally_seat: "ally",
        avalibility: "taken",
      },
      {
        id: 4,
        row: 1,
        row_text: "row_one",
        seat: "D",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 5,
        row: 1,
        row_text: "row_one",
        seat: "E",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 6,
        row: 2,
        row_text: "row_two",
        seat: "F",
        ally_seat: "none",
        avalibility: "taken",
      },
    ],
    row_two: [
      {
        id: 7,
        row: 2,
        row_text: "row_two",
        seat: "A",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 8,
        row: 2,
        row_text: "row_two",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 9,
        row: 2,
        row_text: "row_two",
        seat: "C",
        ally_seat: "ally",
        avalibility: "taken",
      },
      {
        id: 10,
        row: 2,
        row_text: "row_two",
        seat: "D",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 11,
        row: 2,
        row_text: "row_two",
        seat: "E",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 12,
        row: 2,
        row_text: "row_two",
        seat: "F",
        ally_seat: "none",
        avalibility: "available",
      },
    ],
    row_three: [
      {
        id: 13,
        row: 3,
        row_text: "row_three",
        seat: "A",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 14,
        row: 3,
        row_text: "row_three",
        seat: "B",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 15,
        row: 3,
        row_text: "row_three",
        seat: "C",
        ally_seat: "ally",
        avalibility: "available",
      },
      {
        id: 16,
        row: 3,
        row_text: "row_three",
        seat: "D",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 17,
        row: 3,
        row_text: "row_three",
        seat: "E",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 18,
        row: 3,
        row_text: "row_three",
        seat: "F",
        ally_seat: "none",
        avalibility: "available",
      }
    ]
  },
  
  extra_room: {
    available_seats: 8,
    row_one: [
      {
        id: 19,
        row: 4,
        row_text: "row_four",
        seat: "A",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 20,
        row: 4,
        row_text: "row_four",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 21,
        row: 4,
        row_text: "row_four",
        seat: "C",
        ally_seat: "ally",
        avalibility: "taken",
      },
      {
        id: 22,
        row: 4,
        row_text: "row_four",
        seat: "D",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 23,
        row: 4,
        row_text: "row_four",
        seat: "E",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 24,
        row: 4,
        row_text: "row_four",
        seat: "F",
        ally_seat: "none",
        avalibility: "taken",
      },
    ],
    row_two: [
      {
        id: 25,
        row: 5,
        row_text: "row_five",
        seat: "A",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 26,
        row: 5,
        row_text: "row_five",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 27,
        row: 5,
        row_text: "row_five",
        seat: "C",
        ally_seat: "ally",
        avalibility: "taken",
      },
      {
        id: 28,
        row: 5,
        row_text: "row_five",
        seat: "D",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 29,
        row: 5,
        row_text: "row_five",
        seat: "E",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 30,
        row: 5,
        row_text: "row_five",
        seat: "F",
        ally_seat: "none",
        avalibility: "available",
      },
    ],
    row_three: []
  },
  
  
  
  economy: {
    available_seats: 7,
    row_one: [
      {
        id: 37,
        row: 7,
        row_text: "row_four",
        seat: "A",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 38,
        row: 7,
        row_text: "row_four",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 39,
        row: 7,
        row_text: "row_four",
        seat: "C",
        ally_seat: "ally",
        avalibility: "taken",
      },
      {
        id: 40,
        row: 7,
        row_text: "row_four",
        seat: "D",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 41,
        row: 7,
        row_text: "row_four",
        seat: "E",
        ally_seat: "taken",
        avalibility: "available",
      },
      {
        id: 42,
        row: 7,
        row_text: "row_four",
        seat: "F",
        ally_seat: "none",
        avalibility: "taken",
      },
    ],
    row_two: [
      {
        id: 43,
        row: 8,
        row_text: "row_five",
        seat: "A",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 44,
        row: 8,
        row_text: "row_five",
        seat: "B",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 54,
        row: 8,
        row_text: "row_five",
        seat: "C",
        ally_seat: "ally",
        avalibility: "available",
      },
      {
        id: 45,
        row: 8,
        row_text: "row_five",
        seat: "D",
        ally_seat: "none",
        avalibility: "taken",
      },
      {
        id: 46,
        row: 8,
        row_text: "row_five",
        seat: "E",
        ally_seat: "none",
        avalibility: "available",
      },
      {
        id: 47,
        row: 8,
        row_text: "row_five",
        seat: "F",
        ally_seat: "none",
        avalibility: "available",
      },
    ],
    row_three: []
  },
}
