export const Products = [
  {
    id: 1,
    title: "Air Jorden 40 PF 'The Classic",
    category: "Basketball",
    colors: ["White", "Black"],
    range: "High",
    deliveryType: "Free Delivery",
    price: "$200.00",
    image: "https://images.pexels.com/photos/1124466/pexels-photo-1124466.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 2,
    title: "Tatum 3 PF",
    category: "Football",
    colors: ["White"],
    range: "Mid",
    deliveryType: "",
    price: "$180.00",
    image: "https://images.pexels.com/photos/8811377/pexels-photo-8811377.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 3,
    title: "Luka 4 PF 'Navidor'",
    category: "Running",
    colors: ["Blue", "Black", "Pink"],
    range: "Mid",
    deliveryType: "",
    price: "$160.00",
    image: "https://images.pexels.com/photos/1161538/pexels-photo-1161538.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 4,
    title: "LeBrun XXII",
    category: "Jordan",
    colors: ["Beige", "Green"],
    range: "High",
    deliveryType: "",
    price: "$140.00",
    image: "https://images.pexels.com/photos/40662/shoes-footwear-hiking-shoes-walking-40662.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 5,
    title: "KD17 EP",
    category: "Basketball",
    colors: ["Yellow", "Orange"],
    range: "Low",
    deliveryType: "Free Delivery",
    price: "$120.00",
    image: "https://images.pexels.com/photos/2385477/pexels-photo-2385477.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 6,
    title: "Nike Vapor Edge 360 'Untouchable'",
    category: "Football",
    colors: ["Gray", "Blue"],
    range: "Mid",
    deliveryType: "",
    price: "$100.00",
    image: "https://images.pexels.com/photos/7432/pexels-photo.jpg",
    alt: "",
    link: "#",
  },
  {
    id: 7,
    title: "Nike Air Max Impact 4",
    category: "Jordan",
    colors: ["White"],
    range: "High",
    deliveryType: "",
    price: "$80.00",
    image: "https://images.pexels.com/photos/1192043/pexels-photo-1192043.jpeg",
    alt: "",
    link: "#",
  },
  
  
  
  {
    id: 8,
    title: "40 PF 'The Classic",
    category: "Running",
    colors: ["White", "Black"],
    range: "High",
    deliveryType: "Free Delivery",
    price: "$190.00",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 9,
    title: "Tatum 10 PF",
    category: "Football",
    colors: ["White", "Pink"],
    range: "Mid",
    deliveryType: "",
    price: "$170.00",
    image: "https://images.pexels.com/photos/19090/pexels-photo.jpg",
    alt: "",
    link: "#",
  },
  {
    id: 10,
    title: "Luka 4 'Navidor'",
    category: "Running",
    colors: ["Blue", "Purple", "Pink"],
    range: "Mid",
    deliveryType: "",
    price: "$150.00",
    image: "https://images.pexels.com/photos/1070360/pexels-photo-1070360.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 11,
    title: "LeBrun XII",
    category: "Jordan",
    colors: ["Brown", "Green"],
    range: "High",
    deliveryType: "",
    price: "$130.00",
    image: "https://images.pexels.com/photos/16947115/pexels-photo-16947115.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 12,
    title: "KD17 CP16",
    category: "Basketball",
    colors: ["Yellow", "Black"],
    range: "Low",
    deliveryType: "Free Delivery",
    price: "$110.00",
    image: "https://images.pexels.com/photos/2529158/pexels-photo-2529158.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 13,
    title: "Nike 360 'Untouchable'",
    category: "Football",
    colors: ["Gray", "Blue"],
    range: "Mid",
    deliveryType: "",
    price: "$90.00",
    image: "https://images.pexels.com/photos/13450843/pexels-photo-13450843.jpeg",
    alt: "",
    link: "#",
  },
  {
    id: 14,
    title: "Nike Sailor Max Impact 4",
    category: "Jordan",
    colors: ["White"],
    range: "High",
    deliveryType: "",
    price: "$70.00",
    image: "https://images.pexels.com/photos/16947114/pexels-photo-16947114.jpeg",
    alt: "",
    link: "#",
  },
]