const ITEMS = [
  {
    id: 1,
    title: "Floral Graphic T-Shirts",
    brand: "farfetch",
    price: "298.77",
    currency: "USD",
    category: "tops",
    src: "https://cdn.shopify.com/s/files/1/0424/6994/9604/files/WWTWS49_slate_0_540x.jpg",
  },
  {
    id: 2,
    title: "MM6 Maison Margiela T-shirt...",
    brand: "prm",
    price: "266.82",
    currency: "USD",
    category: "tops",
    src: "https://amq-mcq.dam.kering.com/asset/96fd65b8-7ee9-4ed7-8eb9-50f913252e40/Medium/876721QJAGF1435_F.jpg",
  },
  {
    id: 3,
    title: "ACUPUNCTURE 1993 stud-e...",
    brand: "fartech",
    price: "179.70",
    currency: "USD",
    category: "tops",
    src: "https://franka.pt/cdn/shop/files/the_garment_22237_Kirsten_Collar_Shirt_white_000_1.webp",
  },
  {
    id: 4,
    title: "ACUPUNCTURE 1993 Touch...",
    brand: "fartech",
    price: "189.20",
    currency: "USD",
    category: "tops",
    src: "https://boldfactory.pt/cdn/shop/files/topblackfront.jpg",
  },
  {
    id: 5,
    title: "Racer x New Rock Black Boot",
    brand: "Racer Worldwide",
    price: "481.75",
    currency: "USD",
    category: "shoes",
    src: "https://redtape.com/cdn/shop/files/RLL0186_1_1324e335-513d-4206-8e5b-afcfa232da72.jpg",
  },
  {
    id: 6,
    title: "ACUPUNCTURE 1993 distres...",
    brand: "farfetch",
    price: "179.75",
    currency: "USD",
    category: "bottoms",
    src: "https://www.preppersshop.co.uk/cdn/shop/files/german-army-extreme-cold-weather-thermal-quilted-trousers-74736-p.jpg",
  },
  {
    id: 7,
    title: "ACUPUNCTURE 1993 Ocean...",
    brand: "farfetch",
    price: "167.75",
    currency: "USD",
    category: "bottoms",
    src: "https://garments.ie/cdn/shop/files/GERRY-WEBER-_2251_80383_925063-31335_6.jpg",
  },
  {
    id: 8,
    title: "Biker Leather Jacket",
    brand: "Racer Worldwide",
    price: "395.75",
    currency: "USD",
    category: "outerwear",
    src: "https://files.ekmcdn.com/sophey2/images/brando-leather-motorcycle-jacket-40-p.jpg",
  },
  {
    id: 9,
    title: "Biker Leather Jacket",
    brand: "Racer Worldwide",
    price: "195.75",
    currency: "USD",
    category: "bags",
    src: "https://fashionweekdaily.com/wp-content/uploads/2024/11/Story72_1.jpg",
  },
  {
    id: 10,
    title: "Biker Leather Jacket",
    brand: "farfetch",
    price: "295.75",
    currency: "USD",
    category: "bags",
    src: "https://www.luxelink.com.au/cdn/shop/collections/bag-coll-header.jpg",
  },
  {
    id: 11,
    title: "Biker Jacket",
    brand: "farfetch",
    price: "225.75",
    currency: "USD",
    category: "bags",
    src: "https://mygemma.com/cdn/shop/articles/mygemma-WPD-Top-Blog-Image-6.png",
  },
]

const TOTAL_ITEMS = ITEMS.length;
const TOTAL_AMOUNT = ITEMS.reduce((acc, item) => acc + parseInt(item.price), 0);

export const DATA = {
  total_items: TOTAL_ITEMS,
  total_amount: TOTAL_AMOUNT,
  children: ITEMS,
  currency: "USD",
}
