export const data = [
  {
    id: 1,
    name: "Shoreline Hat",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 21.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/9064282/pexels-photo-9064282.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1k",
      icon: "C",
    },
    size: "small",
    category: "fashion",
  },
  {
    id: 2,
    name: "Zephyr Gown",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 43.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/1667077/pexels-photo-1667077.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+2k",
      icon: "C",
    },
    size: "medium",
    category: "men",
  },
  {
    id: 3,
    name: "Aspire Comfortwear",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 67.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/6766385/pexels-photo-6766385.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.5k",
      icon: "C",
    },
    size: "medium",
    category: "men",
  },
  {
    id: 4,
    name: "Shoreline Hat",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 31.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/1089243/pexels-photo-1089243.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "667",
      icon: "C",
    },
    size: "large",
    category: "denim",
  },
  {
    id: 5,
    name: "Zephyr Gown",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 43.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/2327683/pexels-photo-2327683.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.2k",
      icon: "C",
    },
    size: "xlarge",
    category: "dress",
  },
  {
    id: 6,
    name: "Aspire Comfortwear",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 67.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/6006229/pexels-photo-6006229.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+2.1k",
      icon: "C",
    },
    size: "xxlarge",
    category: "fashion",
  },
  {
    id: 7,
    name: "Shoreline Hat",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 21.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/2962207/pexels-photo-2962207.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+2k",
      icon: "C",
    },
    size: "small",
    category: "women",
  },
  {
    id: 8,
    name: "Zephyr Gown",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 43.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/8217912/pexels-photo-8217912.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.3k",
      icon: "C",
    },
    size: "medium",
    category: "men",
  },
  {
    id: 9,
    name: "Aspire Comfortwear",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 67.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/7764611/pexels-photo-7764611.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "102",
      icon: "C",
    },
    size: "large",
    category: "denim",
  },
  {
    id: 10,
    name: "Shoreline Hat",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 21.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/2974600/pexels-photo-2974600.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.9k",
      icon: "C",
    },
    size: "xlarge",
    category: "dress",
  },
  {
    id: 11,
    name: "Zephyr Gown",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 43.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/11943168/pexels-photo-11943168.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.1k",
      icon: "C",
    },
    size: "large",
    category: "women",
  },
  {
    id: 12,
    name: "Aspire Comfortwear",
    short_desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 67.99,
    link_url: "#",
    image: {
      src: "https://images.pexels.com/photos/8052846/pexels-photo-8052846.jpeg",
      width: 2000,
      height: 2000,
      alt: "",
    },
    reviews: {
      label: "Reviews",
      metrics: "+1.4k",
      icon: "C",
    },
    size: "medium",
    category: "men",
  }
]